name: Deploy Resume to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync to S3
      run: aws s3 sync ./resume-website s3://wizfi-bucket --delete --exclude ".git/*" --exclude ".github/*"

